spring:
    profiles:
        active: prod
        include: default,rmq
    datasource:
        url: jdbc:mysql://offshoremsdb.cm5sjo7cm7pi.us-east-1.rds.amazonaws.com:3306/ms_inventory_db
        username: inventory_user
        password: user123
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        show-sql: true 
    rabbitmq:
        addresses: rabbitmq:5672
        host: rabbitmq
        port: 5672
        username: spring
        password: spring

            
---

spring:
    profiles:
        active: cf
        include: rmq
    datasource:
        url: jdbc:mysql://localhost:3306/cf_dev_db
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update

    rabbitmq:
        addresses: localhost:5672
        host: localhost
        port: 5672
        username: guest
        password: guest

server:
    port: 9020
    
---

spring:
    profiles: 
        active: dev
        include: default
    datasource:
        url: jdbc:mysql://localhost:3306/microservices
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        show-sql: true
confirm:
    order:
        request:
          queue: confirmedOrderQueue
          routingKey : confirmOrderRoutingKey
        response:
          queue : confirmOrderResponseQueue2
          routingKey : confirmOrderResponseRoutingKey

cancel:
  order:
    queue: cancelledOrderQueue
    routingKey : cancelOrderRoutingKey


routing:
  key : fixedRoutingKey

dead:
    letter:
        queue:
            name: deadLetterQueue

server:
  port : 9024

queue:
  name : microserviceAppQueue

exchange:
  name : orderToInventoryExchange
  
---

spring:
    profiles:
        active: openshift
        include: rmq
    datasource:
        url: jdbc:mysql://offshoremsdb.cm5sjo7cm7pi.us-east-1.rds.amazonaws.com:3306/ms_inventory_db
        username: inventory_user
        password: user123
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        show-sql: true 
    rabbitmq:
        addresses: localhost:5672
        host: localhost
        port: 5672
        username: guest
        password: guest
   
