spring:
    profiles: prod
    datasource:
        url: jdbc:mysql://localhost:3306/microservices
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        show-sql: true 
server:
    port: 8083
queue:
    name: microserviceAppQueue
exchange:
    name: orderToInventoryExchange
routing:
    key: fixedRoutingKey
cancel:
    order:
        queue:
            name: cancelledOrderQueue
        routingKey: cancelOrderRoutingKey 
confirm:
    order:
        routingKey: confirmOrderRoutingKey
        queue:
            name: confirmedOrderQueue  
        response:
            queue: confirmOrderResponseQueue2
            routingKey: confirmOrderResponseRoutingKey
            
---

spring:
    profiles: k8s
    datasource:
        url: jdbc:mysql://offshoremsdb.cm5sjo7cm7pi.us-east-1.rds.amazonaws.com:3306/ms_inventory_db
        username: inventory_user
        password: user123
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        show-sql: true
rabbitmq:
   addresses: rabbitmq:5672
   host: rabbitmq
   port: 5672
   username: spring
   password: spring