spring:
    profiles: 
        active: prod
        include: default,rmq
    datasource:
        url: jdbc:mysql://offshoremsdb.cm5sjo7cm7pi.us-east-1.rds.amazonaws.com:3306/ms_order_db
        username: order_user
        password: user123
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        show-sql: true
    rabbitmq:
        addresses: rabbitmq:5672
        host: rabbitmq
        port: 5672
        username: spring
        password: spring
    
server:
    port: 8084
inventory:
    host: localhost
    port: 8083
confirm:
  order:
    request: 
        queue : confirmedOrderQueue
        routingKey : confirmOrderRoutingKey
    response:
        queue : confirmOrderResponseQueue2
        routingKey : confirmOrderResponseRoutingKey

cancel:
  order:
    request:
      queue : cancelledOrderQueue
      routingKey : cancelOrderRoutingKey


routing:
  key : fixedRoutingKey

dead:
    letter:
        queue:
            name: deadLetterQueue

server:
  port : 9023

queue:
  name : microserviceAppQueue

exchange:
  name : orderToInventoryExchange
   
---


spring:
    profiles: 
        active: cf
        include: rmq
    datasource:
        url: jdbc:mysql://localhost:3306/microservices
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update

    rabbitmq:
        addresses: localhost:5672
        host: localhost
        port: 5672
        username: guest
        password: guest

server:
    port: 9015
    
---

spring:
    profiles: 
        active: dev
        include: default
    datasource:
        url: jdbc:mysql://localhost:3306/microservices
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
