
spring:
    profiles: prod
    datasource:
        url: jdbc:mysql://offshoremsdb.cm5sjo7cm7pi.us-east-1.rds.amazonaws.com:3306/ms_product_db
        username: product_user
        password: user123
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        show-sql: true
    rabbitmq:
       addresses: rabbitmq:5672
       host: rabbitmq
       port: 5672
       username: spring
       password: spring  
redis: 
    host: redis-sentinel 
    port: 26379

---

spring:
    profiles: dev
    datasource:
        url: jdbc:mysql:localhost:3306/microservices
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        show-sql: true
    rabbitmq:
       addresses: localhost:5672
       host: localhost
       port: 5672
       username: guest
       password: guest
