spring:
    profiles: prod
    datasource:
        url: jdbc:mysql://localhost:3306/sakila
        username: root
        password: password
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        show-sql: true  
server:
  port: 8081