spring:
    profiles: prod
    datasource:
        url: jdbc:mysql://localhost:3306/microservices
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        show-sql: true  
server:
  port: 8081  
  
redis: 
    host:127.0.0.1
redis:
    port:6379
rabbitmq:
   addresses: 10.0.0.35:5671
   host: configmq
   port: 5671
   username: guest
   password: guest